owner: YRA-Tech # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: YRA Tech
    url: https://stage.yratech.com
assignees: # Users to assign downtime issues (optional)
  - umaidshahid
status-website:
  cname: status.yratech.com # Custom domain CNAME
  baseUrl: /upptime # where "repo" is your repository name
  name: YRA Tech Status
